
services:
  - type: web
    name: machine-learning-backend
    env: python
    
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 app:app"
    healthCheckPath: "/"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    buildFilter:
      paths:
        - backend/**
  - type: web
    name: machine-learning-frontend
    env: static
    
    plan: free
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /
        destination: /index.html
    buildFilter:
      paths:
        - frontend/**
